# ---------------------------------------------------------------------------
# Clip_wCursor_v2.py
# Created for ArcGIS 9.3.1
#   (clip generated by ArcGIS/ModelBuilder)
# Attempted cursor mods by a newb, Donovan
# ---------------------------------------------------------------------------

# Import system modules
import sys
import string
import os
import arcgisscripting

# Create the Geoprocessor object
gp = arcgisscripting.create(9.3)

# Load required toolboxes...
gp.AddToolbox("C:/Program Files/ArcGIS/ArcToolbox/Toolboxes/Analysis Tools.tbx")

# Designate a workspace
gp.workspace = r"C:\gis\data"

# Assign variables...
clipto = "grids.shp" # grids to clip to
clipit = "lines.shp" # features to be clipped

# Cursor time...
rows = gp.SearchCursor(clipto)
row = rows.Next()
feat = row.Shape # used as the clip_features in the Clip_analysis
while row:
    n = str(row.NAME) # assign a variable for the processing message based on a field
    print "clipping to: " +n # tells you what grid was clipped
    # Clip_analysis <in_features> <clip_features> <out_feature_class> {cluster_tolerance}
    # output format, grid_1_c.shp, grid_2_c.shp, etc...
    gp.Clip_analysis(clipit, feat, str(row.NAME)+"_c"+".shp", "") #update str if necessary
    row=rows.next()

# reset the array...
del rows
del gp

print "...fin..."
print "no error checking happened, examine your workspace..."
